twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_4_layout.html.twig'
    globals: #permet de déclarer des constantes applicatives
        avatar_upload_path: 'uploads/avatars/'
